### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by WilliamWangPeng** [rui314/8cc#108]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119220926-62267580-bb1f-11eb-9707-183e268a8bfd.png)

thank you  
best regards to you  
William

**Comment by megapro17** [comment]
because that fucking option was removed https://github.com/rui314/8cc/issues/51

**Comment by rui314** [comment]
This is an old project which is superseded by https://github.com/rui314/chibicc. Please try it instead.
