### ISSUE TITLE
Failure on Mac

### ISSUE THREAD

**Issue by fmardini** [rui314/8cc#45]
Hello,

I am on OSX 10.9.5 and `make test` is failing with 

[WARN] cpp.c:628: /usr/include/sys/cdefs.h:81:0: #warning: "Unsupported compiler detected"
[ERROR] parse.c:1904: /usr/include/string.h:81:44: identifier, ( or * are expected, but got )

when I look there I see

#if !defined(__GNUC__) || __GNUC__ < 4

But when running with 
./8cc -D__GNUC__ -a -o h hello.c

I get
zsh: segmentation fault  ./8cc -D__GNUC__ -a -o h hello.c

Should I be including a different set of header files?

Thanks

**Comment by rui314** [comment]
Mac OS header files are peculiar. There are a lot of things to do if you want to run it on Mac OS.
