### ISSUE TITLE
UTF8 Characters not supported

### ISSUE THREAD

**Issue by sebastien** [rui314/8cc#47]
The `Ｉ` character is UTF8, supported by clang and gcc with -std=c11.

```
$ echo "typedef long Ｉtid;" > utf8.c ; 8cc -c utf8.c[ERROR] 
parse.c:2651: utf8.c:1:14: stray character in program: '�'
```

**Comment by rui314** [comment]
We need to support UTF-8 characters in string literals or character literals. But it's probably out of scope of a small compiler to support UTF-8 in identifiers. Support multi-byte characters are hard, so I'll leave it alone.

**Comment by rui314** [comment]
It's supported in d5fc4b63229ceca3e136654c16bd6676f705b57b.
